Repository effortless-mgmt/ems_app, pull requests merged in 2019-01, with the labels that each got.

#41 Add iOS build configuration
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
Labels: tested-on-android, tested-on-ios

#42 Add crashlytics
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/main.dart
  pubspec.yaml
Labels: tested-on-android, tested-on-ios

#84 Feature/change contacts to next appointment
  .gitignore
  android/app/src/main/AndroidManifest.xml
  ios/Podfile
  ios/Runner-Bridging-Header.h
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/Runner/AppDelegate.m
  ios/Runner/Info.plist
  ios/Test.swift
  lib/src/models/appointment.dart
  lib/src/models/substitute.dart
  lib/src/screens/add_screen.dart
  lib/src/screens/appointment_details/appBarDescriptive.dart
  lib/src/screens/appointment_details/appointment_details_screen.dart
  lib/src/screens/appointment_details/contact_widget.dart
  lib/src/screens/appointment_details/maps_widget.dart
  lib/src/widgets/appointment_widget.dart
  lib/src/widgets/calendar/calendar_widget.dart
  lib/src/widgets/navbar_widget.dart
  lib/src/widgets/timereg_widget.dart
  lib/util/date_utils.dart
  pubspec.yaml
Labels: UI, enhancement, tested-on-android, tested-on-ios

#86 Script to automatically setup development environemtn
  README.md
  ios/Runner.xcodeproj/project.pbxproj
  setup-development.sh
Labels: enhancement, tested-on-android, tested-on-ios

#90 Feature/refine add screen
  lib/main.dart
  lib/src/models/appointment.dart
  lib/src/models/substitute.dart
  lib/src/screens/add_screen.dart
  lib/src/screens/calendar_screen.dart
  lib/src/screens/home_screen.dart
  lib/src/screens/profile_screen.dart
  lib/src/widgets/add_time_widget.dart
  lib/src/widgets/navbar_widget.dart
  lib/src/widgets/timereg_widget.dart
Labels: UI, enhancement, feature, tested-on-android, tested-on-ios

#114 Minor cleanup
  lib/src/app.dart
  lib/src/bloc/auth/auth.dart
  lib/src/bloc/auth/auth_bloc.dart
  lib/src/bloc/auth/auth_event.dart
  lib/src/bloc/auth/auth_state.dart
  lib/src/bloc/login/login.dart
  lib/src/bloc/login/login_bloc.dart
  lib/src/bloc/login/login_event.dart
  lib/src/bloc/login/login_state.dart
  lib/src/bloc/login/validator.dart
  lib/src/bloc/nav/navbar.dart
  lib/src/bloc/nav/navbar_bloc.dart
  lib/src/bloc/nav/navbar_event.dart
  lib/src/bloc/nav/navbar_state.dart
  lib/src/blocs/nav/bloc.dart
  lib/src/blocs/nav/bloc_provider.dart
  lib/src/blocs/nav/transformer.dart
  lib/src/providers/user_api_provider.dart
  lib/src/screens/login_screen.dart
  lib/src/widgets/custom_nav_bar.dart
Labels: BL, enhancement, tested-on-android

#117 Feature/job offer screen
  ios/Runner.xcodeproj/project.pbxproj
  lib/src/bloc/nav/navbar_bloc.dart
  lib/src/models/appointment.dart
  lib/src/screens/appointment_details/appBarDescriptive.dart
  lib/src/screens/appointment_details/appointment_details_screen.dart
  lib/src/screens/appointment_details/maps_widget.dart
  lib/src/screens/appointment_details/next_appointment_details_screen.dart
  lib/src/screens/home_screen.dart
Labels: UI, enhancement, feature, substitute specific, tested-on-android

#91 Implemented all the basics of settings
  assets/black.png
  assets/blue.png
  assets/red.png
  ios/Runner.xcodeproj/project.pbxproj
  lib/main.dart
  lib/src/app.dart
  lib/src/bloc/settings/settings.dart
  lib/src/bloc/settings/settings_bloc.dart
  lib/src/bloc/settings/settings_event.dart
  lib/src/bloc/settings/settings_state.dart
  lib/src/screens/login_screen.dart
  lib/src/screens/settings/calendar_setting_screen.dart
  lib/src/screens/settings/change_password_setting_screen.dart
  lib/src/screens/settings/preferences.dart
  lib/src/screens/settings/theme_screen.dart
  lib/src/screens/settings_screen.dart
  pubspec.yaml
Labels: BL, UI, enhancement, feature, tested-on-android, tested-on-ios

#144 Feature/home enhancement
  lib/src/models/appointment.dart
  lib/src/screens/appointment_details/appBarDescriptive.dart
  lib/src/screens/appointment_details/appointment_details_screen.dart
  lib/src/screens/appointment_details/maps_widget.dart
  lib/src/screens/home_screen.dart
  lib/src/screens/home_screen/all_shifts_screen.dart
  lib/src/screens/home_screen/appointment_list.dart
  lib/src/screens/home_screen/page_routes.dart
  lib/src/screens/home_screen/show_all_button.dart
  lib/src/util/date_utils.dart
Labels: UI, enhancement, feature, tested-on-android

#118 Feature/icon badges
  lib/src/widgets/custom_nav_bar.dart
Labels: UI, enhancement, feature, tested-on-android

#151 Feature/maps fix
  lib/src/screens/appointment_details/maps_widget.dart
Labels: enhancement, tested-on-android, tested-on-ios

#152 Fixed issues with home_screen, added icons and whatnot.
  lib/src/app.dart
  lib/src/screens/add_screen.dart
  lib/src/screens/home_screen.dart
  lib/src/screens/home_screen/appointment_list.dart
  lib/src/screens/home_screen/show_all_button.dart
  lib/src/screens/messenger_screen.dart
  lib/src/widgets/add_time_widget.dart
Labels: UI, bug, enhancement, tested-on-android

#155 Feature/prepare user test
  lib/main.dart
  lib/src/app.dart
  lib/src/bloc/nav/navbar_bloc.dart
  lib/src/models/appointment.dart
  lib/src/screens/add_screen.dart
  lib/src/screens/appointment_details/appBarDescriptive.dart
  lib/src/screens/appointment_details/appointment_details_screen.dart
  lib/src/screens/appointment_details/contact_widget.dart
  lib/src/screens/appointment_details/maps_widget.dart
  lib/src/screens/home_screen/all_shifts_screen.dart
  lib/src/screens/home_screen/appointment_list.dart
  lib/src/screens/login_screen.dart
  lib/src/screens/messenger_screen.dart
  lib/src/screens/profile_screen.dart
  lib/src/screens/settings/calendar_setting_screen.dart
  lib/src/screens/settings/change_password_setting_screen.dart
  lib/src/screens/settings/theme_screen.dart
  lib/src/screens/settings_screen.dart
  lib/src/util/jwt_utils.dart
  lib/src/util/user.dart
  lib/src/widgets/add_time_widget.dart
  lib/src/widgets/appointment_widget.dart
  lib/src/widgets/custom_icons/settings_icon.dart
  lib/src/widgets/custom_nav_bar.dart
Labels: UI, bug, enhancement, tested-on-android, tested-on-ios, user test

#157 Change color of "Send" button and commit iOS stuff
  ios/Runner.xcodeproj/project.pbxproj
  lib/src/screens/messenger_screen.dart
Labels: UI, bug, tested-on-ios

#158 Implemented appointment BLoC pattern
  lib/src/app.dart
  lib/src/bloc/appointment/appointment.dart
  lib/src/bloc/appointment/appointment_bloc.dart
  lib/src/bloc/appointment/appointment_event.dart
  lib/src/bloc/appointment/appointment_repo.dart
  lib/src/bloc/appointment/appointment_state.dart
  lib/src/bloc/auth/auth_bloc.dart
  lib/src/bloc/auth/auth_event.dart
  lib/src/bloc/auth/auth_repo.dart
  lib/src/bloc/auth/auth_state.dart
  lib/src/bloc/login/login_bloc.dart
  lib/src/bloc/nav/navbar_bloc.dart
  lib/src/models/DEMO/appointment.dart
  lib/src/models/DEMO/user.dart
  lib/src/models/DEMO/user_list.dart
  lib/src/models/appointment.dart
  lib/src/models/substitute.dart
  lib/src/models/user.dart
  lib/src/providers/appointment_api_provider.dart
  lib/src/providers/auth_api_provider.dart
  lib/src/providers/auth_item_model.dart
  lib/src/providers/user_api_provider.dart
  lib/src/screens/add_screen.dart
  lib/src/screens/appointment_details/appBarDescriptive.dart
  lib/src/screens/appointment_details/appointment_details_screen.dart
  lib/src/screens/appointment_details/contact_widget.dart
  lib/src/screens/appointment_details/next_appointment_details_screen.dart
  lib/src/screens/calendar_screen.dart
  lib/src/screens/contacts/contacts_card.dart
  lib/src/screens/contacts/contacts_screen.dart
  lib/src/screens/home_screen.dart
  lib/src/screens/home_screen/all_shifts_screen.dart
  lib/src/screens/home_screen/appointment_list.dart
  lib/src/screens/home_screen/show_all_button.dart
  lib/src/screens/nav_bar_screens.dart
  lib/src/screens/overview_screen.dart
  lib/src/screens/profile_screen.dart
  lib/src/util/jwt_utils.dart
  lib/src/util/user_list.dart
  lib/src/widgets/add_time_widget.dart
  lib/src/widgets/appointment_widget.dart
  lib/src/widgets/calendar/calendar_widget.dart
Labels: BL, enhancement, feature, important, tested-on-android, tested-on-ios

#159 Update version to v0.0.2-alpha
  android/app/build.gradle
  pubspec.yaml
Labels: enhancement

#147 Feature/test
  pubspec.yaml
  test/authentication_bloc_test.dart
  test/login_bloc_test.dart
  test/theme_settings_widget_test.dart
  test/widget_test.dart
Labels: tested-on-android, tested-on-ios

#160 Fixed bug where appointment got deleted locally before event could be…
  lib/src/screens/add_screen.dart
Labels: bug, important, substitute specific, tested-on-android

#161 Nothingtoseehere
  lib/main.dart
  lib/src/app.dart
  lib/src/bloc/appointment/appointment_bloc.dart
  lib/src/bloc/nav/navbar_bloc.dart
  lib/src/models/DEMO/substitute.dart
  lib/src/screens/appointment_details/appointment_details_screen.dart
  lib/src/screens/appointment_details/next_appointment_details_screen.dart
  lib/src/screens/calendar_screen.dart
  lib/src/screens/home_screen/all_shifts_screen.dart
  lib/src/screens/home_screen/appointment_list.dart
  lib/src/screens/overview_screen.dart
  lib/src/screens/profile_screen.dart
  lib/src/util/date_utils.dart
  lib/src/widgets/add_time_widget.dart
  lib/src/widgets/appointment_widget.dart
  lib/src/widgets/calendar/calendar_tile.dart
  lib/src/widgets/calendar/calendar_widget.dart
Labels: important, tested-on-android
